Settings:
  Prefix: '&8[&6Planet&8] &7'
  BlocksPerTick: 500
  ProtectedZoneRadius: 30
   # in the protected zone, players can't execute the blocked commands
  BlockedCommands:
    - /tp
    - /give
    - /kill

Command:
  Tp:
    # coolown in seconds
    cooldown: 120